"use client";

import { useMemo, useState } from "react";
import { Download, Copy, Check, Workflow } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import type { Project, Workspace } from "@/lib/workspace/schema";
import {
  buildPrismaCounts,
  prismaCountsText,
  type PrismaCounts,
} from "@/lib/workspace/prisma-flow";

interface PrismaDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  searches: Workspace["searches"];
  project: Project;
}

/**
 * Literal palettes (not CSS vars) so the generated SVG is standalone —
 * the downloaded file keeps Solarized colors without the stylesheet.
 */
const PALETTE = {
  light: {
    bg: "#fdf6e3",
    ink: "#073642",
    body: "#586e75",
    border: "#657b83",
    boxFill: "#eee8d5",
    sideFill: "#f5efdc",
    cyan: "#2aa198",
    cyanInk: "#17766c",
    orange: "#cb4b16",
    orangeInk: "#b2430e",
    green: "#859900",
    greenInk: "#6d7a00",
    magenta: "#d33682",
    yellow: "#b58900",
  },
  dark: {
    bg: "#073642",
    ink: "#eee8d5",
    body: "#93a1a1",
    border: "#586e75",
    boxFill: "#0a3d4a",
    sideFill: "#012630",
    cyan: "#2aa198",
    cyanInk: "#45c7b5",
    orange: "#cb4b16",
    orangeInk: "#e56a35",
    green: "#859900",
    greenInk: "#aeba19",
    magenta: "#d33682",
    yellow: "#b58900",
  },
} as const;

function FlowBox({
  x,
  y,
  w,
  h,
  title,
  count,
  fill,
  stroke,
  ink,
  body,
  strong,
  compact,
}: {
  x: number;
  y: number;
  w: number;
  h: number;
  title: string;
  count: number;
  fill: string;
  stroke: string;
  ink: string;
  body: string;
  strong?: boolean;
  compact?: boolean;
}) {
  const lines = title.split("\n");
  const titleStart = compact ? 15 : 20;
  const lineGap = compact ? 13 : 15;
  const countY = compact ? h - 6 : h - 12;
  return (
    <g>
      <rect
        x={x}
        y={y}
        width={w}
        height={h}
        rx={2}
        fill={fill}
        stroke={stroke}
        strokeWidth={strong ? 2.5 : 2}
      />
      {lines.map((line, i) => (
        <text
          key={i}
          x={x + w / 2}
          y={y + titleStart + i * lineGap}
          textAnchor="middle"
          fontFamily="IBM Plex Mono, Menlo, monospace"
          fontSize={compact ? 10 : 11}
          fill={body}
        >
          {line}
        </text>
      ))}
      <text
        x={x + w / 2}
        y={y + countY}
        textAnchor="middle"
        fontFamily="IBM Plex Mono, Menlo, monospace"
        fontSize={compact ? 11 : 15}
        fontWeight={700}
        fill={ink}
      >
        {compact ? `n = ${count.toLocaleString()}` : `(n = ${count.toLocaleString()})`}
      </text>
    </g>
  );
}

function StageLabel({
  y,
  label,
  ink,
}: {
  y: number;
  label: string;
  ink: string;
}) {
  return (
    <text
      x={16}
      y={y}
      fontFamily="IBM Plex Mono, Menlo, monospace"
      fontSize={10}
      fontWeight={700}
      letterSpacing={1.5}
      fill={ink}
      transform={`rotate(-90 16 ${y})`}
      textAnchor="end"
    >
      {label.toUpperCase()}
    </text>
  );
}

function PrismaSvg({
  counts,
  palette,
  projectName,
}: {
  counts: PrismaCounts;
  /** light or dark literal palette — both render standalone SVGs */
  palette: (typeof PALETTE)[keyof typeof PALETTE];
  projectName: string;
}) {
  // Layout constants
  const W = 620;
  const H = 560;
  const mainX = 130;
  const mainW = 340;
  const sideX = 500;
  const sideW = 110;
  const rowH = 64;
  const rows = [110, 214, 318, 438];
  const cx = mainX + mainW / 2;

  return (
    <svg
      viewBox={`0 0 ${W} ${H}`}
      width="100%"
      role="img"
      aria-label={`PRISMA flow diagram for ${projectName}`}
      style={{ background: palette.bg, borderRadius: 2, display: "block" }}
    >
      {/* Title */}
      <text x={mainX} y={30} fontFamily="IBM Plex Mono, Menlo, monospace" fontSize={12} fontWeight={700} fill={palette.ink}>
        PRISMA-style flow · {projectName.slice(0, 42)}
      </text>
      <text x={mainX} y={46} fontFamily="IBM Plex Mono, Menlo, monospace" fontSize={9} fill={palette.body}>
        Generated by KIVO — The Evidence Desk · {new Date().toISOString().slice(0, 10)}
      </text>

      {/* Stage labels */}
      <StageLabel y={rows[0] + rowH / 2} label="Identification" ink={palette.cyanInk} />
      <StageLabel y={rows[1] + rowH / 2 + 20} label="Screening" ink={palette.orangeInk} />
      <StageLabel y={rows[3] + rowH / 2} label="Included" ink={palette.greenInk} />

      {/* Row 1 — identified */}
      <FlowBox x={mainX} y={rows[0]} w={mainW} h={rowH} title={"Records identified from\nscholarly databases (all searches)"} count={counts.identified} fill={palette.boxFill} stroke={palette.border} ink={palette.ink} body={palette.body} strong />
      {/* side: duplicates */}
      <FlowBox x={sideX} y={rows[0] - 6} w={sideW} h={rowH - 8} compact title={"Duplicate\nrecords removed"} count={counts.duplicatesRemoved} fill={palette.sideFill} stroke={palette.border} ink={palette.body} body={palette.body} />
      <line x1={mainX + mainW} y1={rows[0] + rowH / 2} x2={sideX} y2={rows[0] + rowH / 2 - 4} stroke={palette.border} strokeWidth={2} />
      <text x={(mainX + mainW + sideX) / 2} y={rows[0] + rowH / 2 - 8} textAnchor="middle" fontFamily="IBM Plex Mono, Menlo, monospace" fontSize={9} fill={palette.body}>−</text>

      {/* Row 2 — unique records */}
      <FlowBox x={mainX} y={rows[1]} w={mainW} h={rowH} title={"Unique records retained\nafter deduplication"} count={counts.uniqueIdentified} fill={palette.boxFill} stroke={palette.border} ink={palette.ink} body={palette.body} />
      <line x1={cx} y1={rows[0] + rowH} x2={cx} y2={rows[1]} stroke={palette.border} strokeWidth={2} />

      {/* Row 3 — queued for screening */}
      <FlowBox x={mainX} y={rows[2]} w={mainW} h={rowH} title={"Records queued for\nscreening in this project"} count={counts.queued} fill={palette.boxFill} stroke={palette.border} ink={palette.ink} body={palette.body} strong />
      <line x1={cx} y1={rows[1] + rowH} x2={cx} y2={rows[2]} stroke={palette.border} strokeWidth={2} />

      {/* side: excluded + held */}
      <FlowBox x={sideX} y={rows[2] - 4} w={sideW} h={38} compact title="Excluded" count={counts.excluded} fill={palette.sideFill} stroke={palette.orange} ink={palette.orangeInk} body={palette.orangeInk} />
      <FlowBox x={sideX} y={rows[2] + 38} w={sideW} h={38} compact title="Held as maybe" count={counts.maybe} fill={palette.sideFill} stroke={palette.magenta} ink={palette.magenta} body={palette.magenta} />
      <line x1={mainX + mainW} y1={rows[2] + rowH / 2} x2={sideX} y2={rows[2] + 15} stroke={palette.border} strokeWidth={2} />
      <line x1={mainX + mainW} y1={rows[2] + rowH / 2} x2={sideX} y2={rows[2] + 57} stroke={palette.border} strokeWidth={2} />

      {/* Row 4 — included */}
      <FlowBox x={mainX} y={rows[3]} w={mainW} h={rowH} title={"Studies included in review\n(screening decisions)"} count={counts.included} fill={palette.boxFill} stroke={palette.green} ink={palette.greenInk} body={palette.body} strong />
      <line x1={cx} y1={rows[2] + rowH} x2={cx} y2={rows[3]} stroke={palette.border} strokeWidth={2} />

      {/* Footnote */}
      <text x={mainX} y={H - 22} fontFamily="IBM Plex Mono, Menlo, monospace" fontSize={9} fill={palette.body}>
        {`Not yet screened: ${counts.unscreened} · Searches counted: ${counts.searchesCounted}`}
      </text>
      <text x={mainX} y={H - 8} fontFamily="IBM Plex Mono, Menlo, monospace" fontSize={9} fill={palette.body}>
        Single-reviewer, single-stage flow. Every decision is logged as an audit event.
      </text>
    </svg>
  );
}

export function PrismaDialog({
  open,
  onOpenChange,
  searches,
  project,
}: PrismaDialogProps) {
  const [copied, setCopied] = useState(false);

  const counts = useMemo(
    () => buildPrismaCounts(searches, project),
    [searches, project]
  );

  // Read the active theme at render time — the dialog only opens via user
  // interaction (post-hydration), so this is always a client-side read. The
  // SVG uses literal colors so the downloaded file is standalone.
  const isDark =
    typeof document !== "undefined" &&
    document.documentElement.classList.contains("dark");

  const palette = isDark ? PALETTE.dark : PALETTE.light;

  const handleDownloadSvg = () => {
    const svg = document.getElementById("kivo-prisma-svg");
    if (!svg) return;
    const clone = svg.cloneNode(true) as SVGElement;
    clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");
    const serialized = new XMLSerializer().serializeToString(clone);
    const blob = new Blob([serialized], { type: "image/svg+xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `prisma-${project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40)}.svg`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyCounts = async () => {
    try {
      await navigator.clipboard.writeText(
        prismaCountsText(counts, project.name)
      );
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* clipboard unavailable */
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="!max-w-2xl !bg-[var(--bg-paper)] !border-2 !border-[var(--border-ink)] !rounded-[var(--radius-cut)] !shadow-[6px_6px_0_rgba(101,123,131,0.25)] !p-0 max-h-[92vh] overflow-y-auto">
        <DialogHeader className="p-5 pb-0">
          <DialogTitle className="!font-display !text-xl font-extrabold !text-[var(--ink-heading)] flex items-center gap-2.5">
            <Workflow className="w-5 h-5 text-[var(--cyan-ink)]" strokeWidth={2.2} />
            PRISMA-style flow diagram
          </DialogTitle>
          <DialogDescription className="!text-[var(--ink-body)] text-sm">
            Counts derive from your workspace search history and this project&apos;s
            screening decisions — ready to paste into a methods section.
          </DialogDescription>
        </DialogHeader>

        <div className="p-5 space-y-4">
          {/* Diagram */}
          <div id="kivo-prisma-svg" className="bench-card !shadow-none p-3">
            <PrismaSvg counts={counts} palette={palette} projectName={project.name} />
          </div>

          {/* Actions */}
          <div className="flex flex-wrap items-center gap-2.5">
            <button
              type="button"
              onClick={handleDownloadSvg}
              className="btn btn-primary btn-chip text-[11px] font-mono uppercase tracking-wider"
            >
              <Download className="w-3.5 h-3.5" strokeWidth={2.4} />
              <span>Download SVG</span>
            </button>
            <button
              type="button"
              onClick={handleCopyCounts}
              className="btn btn-ghost btn-chip text-[11px] font-mono uppercase tracking-wider"
            >
              {copied ? (
                <Check className="w-3.5 h-3.5 text-[var(--green-ink)]" strokeWidth={2.6} />
              ) : (
                <Copy className="w-3.5 h-3.5" strokeWidth={2.2} />
              )}
              <span>{copied ? "Copied" : "Copy counts as text"}</span>
            </button>
          </div>

          {/* Exclusion reasons */}
          {counts.exclusionReasons.length > 0 && (
            <div className="space-y-2">
              <h4 className="stamp-label">
                <span className="stamp-underline">Exclusion reasons</span>
              </h4>
              <div className="bench-card !shadow-none !p-0 overflow-hidden">
                <table className="bench-table">
                  <thead>
                    <tr>
                      <th className="text-left">Reason</th>
                      <th className="text-center">Records</th>
                    </tr>
                  </thead>
                  <tbody>
                    {counts.exclusionReasons.map((r) => (
                      <tr key={r.reason}>
                        <td className="text-left">{r.reason}</td>
                        <td className="text-center font-mono font-bold text-[var(--orange-ink)]">
                          {r.count}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* KPI strip */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
            <div className="stat-cell !p-3">
              <span className="stat-label">Identified</span>
              <span className="stat-value !text-2xl">{counts.identified}</span>
            </div>
            <div className="stat-cell tone-orange !p-3">
              <span className="stat-label">Duplicates</span>
              <span className="stat-value !text-2xl text-[var(--orange-ink)]">{counts.duplicatesRemoved}</span>
            </div>
            <div className="stat-cell tone-red !p-3">
              <span className="stat-label">Excluded</span>
              <span className="stat-value !text-2xl text-[var(--red-ink)]">{counts.excluded}</span>
            </div>
            <div className="stat-cell tone-green !p-3">
              <span className="stat-label">Included</span>
              <span className="stat-value !text-2xl text-[var(--green-ink)]">{counts.included}</span>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
