import type { Project, Workspace } from "./schema";

/**
 * PRISMA 2020 flow counts, derived honestly from the local workspace.
 *
 * Mapping (single-reviewer, single-stage screening — the KIVO model):
 * - "Records identified from databases"  = sum of records returned across all
 *   recorded searches in the workspace.
 * - "Duplicate records removed"          = identified − unique records (the
 *   same paper surfacing in multiple searches or sources).
 * - "Records queued for screening"        = project members.
 * - "Records excluded"                    = members with decision "exclude",
 *   grouped by the researcher's own reasons.
 * - "Held as maybe / unscreened"          = KIVO's explicit undecided states
 *   (shown transparently even though classic PRISMA omits them).
 * - "Studies included in review"          = members with decision "include".
 */
export interface PrismaCounts {
  identified: number;
  uniqueIdentified: number;
  duplicatesRemoved: number;
  queued: number;
  excluded: number;
  maybe: number;
  unscreened: number;
  included: number;
  exclusionReasons: Array<{ reason: string; count: number }>;
  searchesCounted: number;
}

/** DOI-identity key matching the workspace normalizer's dedup rule. */
function identityKey(paper: { id: string; doi: string | null }): string {
  return paper.doi ? `doi:${paper.doi.toLowerCase()}` : paper.id;
}

export function buildPrismaCounts(
  searches: Workspace["searches"],
  project: Project
): PrismaCounts {
  // Records identified: every record every recorded search returned.
  const identified = searches.reduce(
    (sum, s) => sum + (Array.isArray(s.papers) ? s.papers.length : 0),
    0
  );

  // Unique records: dedupe by DOI identity across searches.
  const seen = new Set<string>();
  for (const s of searches) {
    for (const p of s.papers || []) seen.add(identityKey(p));
  }
  const uniqueIdentified = seen.size;

  const members = project.members;
  const excludedMembers = members.filter((m) => m.decision === "exclude");

  // Group exclusion reasons (blank reasons grouped under "No reason recorded").
  const reasonMap = new Map<string, number>();
  for (const m of excludedMembers) {
    const key = m.reason.trim() || "No reason recorded";
    reasonMap.set(key, (reasonMap.get(key) ?? 0) + 1);
  }
  const exclusionReasons = [...reasonMap.entries()]
    .map(([reason, count]) => ({ reason, count }))
    .sort((a, b) => b.count - a.count || a.reason.localeCompare(b.reason));

  return {
    identified,
    uniqueIdentified,
    duplicatesRemoved: Math.max(0, identified - uniqueIdentified),
    queued: members.length,
    excluded: excludedMembers.length,
    maybe: members.filter((m) => m.decision === "maybe").length,
    unscreened: members.filter((m) => m.decision === "unscreened").length,
    included: members.filter((m) => m.decision === "include").length,
    exclusionReasons,
    searchesCounted: searches.length,
  };
}

/** Plain-text summary suitable for pasting into a methods section. */
export function prismaCountsText(
  counts: PrismaCounts,
  projectName: string
): string {
  const lines = [
    `PRISMA-style screening summary — ${projectName}`,
    `Generated by KIVO on ${new Date().toISOString().slice(0, 10)}`,
    "",
    `Records identified across ${counts.searchesCounted} recorded search(es): ${counts.identified}`,
    `  Unique records after duplicate removal: ${counts.uniqueIdentified} (${counts.duplicatesRemoved} duplicate record(s) removed)`,
    `Records queued for screening: ${counts.queued}`,
    `  Excluded at screening: ${counts.excluded}`,
    `  Held as maybe: ${counts.maybe}`,
    `  Not yet screened: ${counts.unscreened}`,
    `Studies included in review: ${counts.included}`,
  ];
  if (counts.exclusionReasons.length > 0) {
    lines.push("", "Exclusion reasons:");
    for (const r of counts.exclusionReasons) {
      lines.push(`  - ${r.reason}: ${r.count}`);
    }
  }
  lines.push(
    "",
    "Counts derive from the local workspace search history and the project's",
    "screening decisions (each decision is recorded as an audit event)."
  );
  return lines.join("\n");
}
